<?php

namespace Firebird\Query\Grammars;

use Firebird\Query\Grammars\Firebird25Grammar;
use Illuminate\Database\Query\Builder;


class Firebird30Grammar extends Firebird25Grammar
{
    protected $selectComponents = [
        'aggregate',
        'columns',
        'from',
        'joins',
        'wheres',
        'groups',
        'havings',
        'orders',
        'offset',
        'limit',
        'unions',
        'lock',
    ];

    protected function compileLimit(Builder $query, $limit)
    {
        //return parent::compileLimit($query, $limit); // TODO: Change the autogenerated stub
        if ($limit) {
            return 'fetch first ' . (int) $limit . ' rows only';
        } else {
            return null;
        }
    }

    protected function compileOffset(Builder $query, $offset)
    {
        //return parent::compileOffset($query, $offset); // TODO: Change the autogenerated stub

        if ($offset) {
            return 'offset ' . (int) $offset . ' rows';
        } else {
            return null;
        }
    }

}